# Generated by Django 4.2.1 on 2023-05-23 18:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_myuser_remove_employeeuser_user_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
